# Generated by Django 5.2.8 on 2025-11-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('media_file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], default='photo', max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
