# Generated by Django 5.2.7 on 2025-12-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_mediafiles_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('gif', 'GIF'), ('video', 'Видео'), ('audio', 'Аудио')], default='photo', max_length=10, verbose_name='Тип'),
        ),
    ]
