# Generated by Django 5.2.8 on 2025-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='materials/videos/'),
        ),
    ]
