# Generated by Django 5.2.8 on 2025-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
