# Generated by Django 5.2.5 on 2025-11-29 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField()),
                ('question', models.CharField()),
                ('other_content', models.CharField(null=True)),
                ('media', models.ImageField(null=True, upload_to='')),
                ('quick_ans_YES', models.IntegerField()),
                ('quick_ans_NO', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('media', models.ImageField(null=True, upload_to='')),
                ('reaction', models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE'), ('BEST', 'BEST')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.theme')),
            ],
        ),
    ]
