# Generated by Django 5.2.5 on 2025-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='quick_ans_NO',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='quick_ans_YES',
        ),
        migrations.AlterField(
            model_name='theme',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
