# Generated by Django 5.2.5 on 2025-12-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_theme_quick_ans_no_remove_theme_quick_ans_yes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
