# Generated by Django 5.2.5 on 2025-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_posts_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='posts_static/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='theme_static/'),
        ),
    ]
