# Generated by Django 5.2.5 on 2025-11-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва голосування')),
                ('description', models.TextField(verbose_name='Опис голосування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата початку')),
                ('end_date', models.BooleanField(blank=True, default=True, verbose_name='Дата завершення')),
                ('allow_revote', models.BooleanField(default=True, verbose_name='Дозволити переголосування')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонімне голосування')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_votes', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'verbose_name': 'Голосування',
                'verbose_name_plural': 'Голосування',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варіанту')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.vote', verbose_name='Голосування')),
            ],
            options={
                'verbose_name': 'Варіант голосування',
                'verbose_name_plural': 'Варіанти голосування',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час голосування')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_responses', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('vote_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='voting.voteoption', verbose_name='Обраний варіант')),
            ],
            options={
                'verbose_name': 'Відповідь користувача',
                'verbose_name_plural': 'Відповіді користувачів',
                'ordering': ['-voted_at'],
            },
        ),
    ]
