# Generated by Django 5.2.5 on 2025-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
    ]
